ADDRESSES = hierarchy = {'United Kingdom':
                            {'Exeter, Devon':
                                {'Topsham':
                                    ['Hamilton Road',
                                     'Strand',
                                     'Wendover Way',
                                     'Western Avenue',
                                     'Ashford Road',
                                     'Tollards Road',
                                     'Tresilian Gardens',
                                     'Ludwell Lane',
                                     'Rydon Lane',
                                     'Altamira',
                                     'Old Rydon Close',
                                     'Bishop Westall Road',
                                     'Monmouth Hill',
                                     'Victoria Road',
                                     'North Street',
                                     'Elm Grove Avenue',
                                     'Bowling Green Road',
                                     'Moonridge',
                                     'Topsham Road',
                                     'Pynes Hill',
                                     'River Plate Road',
                                     'Rivers Walk',
                                     'Station Road',
                                     'Bridge Hill',
                                     'The Copse',
                                     'Liberty Way',
                                     'Pound Lane',
                                     'Globe Lane',
                                     'High Street',
                                     'Underhill Terrace',
                                     'Resolution Road',
                                     'Strand View',
                                     'Lower Shapter Street',
                                     'Gordon Road',
                                     'Denver Close',
                                     'Southbrook Road',
                                     'Highfield',
                                     'Orchard Way',
                                     'Newcourt Road',
                                     'Exe Street',
                                     'Balmoral Gardens',
                                     'Ferry Road',
                                     'Globefield',
                                     'Exeter Road',
                                     'The Mede',
                                     'Monmouth Avenue',
                                     'Elm Grove Gardens',
                                     'Caroline Avenue',
                                     'Holman Way',
                                     'Old Rydon Lane',
                                     'Swallowfield Road',
                                     'Wessex Close',
                                     'Omaha Drive',
                                     'Denver Road',
                                     'Higher Shapter Close',
                                     'Greatwood Terrace',
                                     'Haldon Close',
                                     'Tappers Close',
                                     'Eastern Avenue',
                                     'Fore Street',
                                     'Rhode Island Drive',
                                     'Sidmouth Road',
                                     'Robert Davey Road',
                                     'Clyst Road',
                                     'Sir Alex Walk',
                                     'Towerfield',
                                     'Grove Hill',
                                     'Nurseries Close',
                                     'Parkfield Road',
                                     'Sunhill Avenue',
                                     'Retreat Road',
                                     'Batavia Drive',
                                     'Russell Way',
                                     'Nelson Close',
                                     'Jutland Way',
                                     'Central Avenue',
                                     'Monmouth Street',
                                     'Second Avenue',
                                     'White Street',
                                     'Follett Road',
                                     'Riverside Road',
                                     'Belvedere Close',
                                     'Pound Close',
                                     'Powderham Close',
                                     'Bridgehill Garth',
                                     'Elm Grove Road',
                                     'First Avenue',
                                     'Higher Shapter Street',
                                     'Old Rydon Ley',
                                     'The Retreat Drive',
                                     'Third Avenue']},
                             'Hammersmith & Fulham, London':
                                {'Fulham': ['Munster Road',
                                              'Fulham Palace '
                                              'Road',
                                              "New King's "
                                              'Road'],
                                 'Hammersmith': ['Talgarth '
                                                   'Road',
                                                   'Hammersmith '
                                                   'Road']},
                              'Kingston-upon-Thames, London':
                                 {'':
                                      ['Richmond Road',
                                      'London Road',
                                      'Kingston Hill'],
                                  'New Malden':
                                      ['Salisbury '
                                       'Road',
                                       'Coombe '
                                       'Road']},
                               'Lambeth, London':
                                  {'Brixton':
                                       ['Acre Lane',
                                        'Town Hall Parade'],
                               'Clapham Town':
                                       ['The Pavement',
                                        'Venn Street',
                                        'Clapham High '
                                        'Street']},
                              'Merton, London':
                                    {'Mitcham':
                                     ['Croydon Road',
                                      'Madeira Road'],
                              'Morden':
                                     ['St Helier Avenue',
                                      'Central Road',
                                      'London Road']},
                              'Wandsworth, London':
                                 {'Balham':
                                   ['Royal Duchess Mews',
                                    'Harberson Road',
                                    'Beira Street',
                                    'Gaskarth Road',
                                    'Amner Road',
                                    'Wroughton Road',
                                    'Caistor Road',
                                    'Martindale Road',
                                    'Earlsthorpe Mews',
                                    'Lammermoor Road',
                                    'Cathles Road',
                                    'Caister Mews',
                                    'Old Devonshire Road',
                                    'Walsingham Place',
                                    'Alderbrook Road',
                                    'Grove Place',
                                    'Hillier Road',
                                    'Malwood Road',
                                    'Ranmere Street',
                                    'Bedford Hill',
                                    'Lysias Road',
                                    'Shipka Road',
                                    'Windmill Drive',
                                    'Bellamy Street',
                                    'Morella Road',
                                    'Broomwood Road',
                                    'Balham High Road',
                                    'Granard Road',
                                    'Ravenswood Road',
                                    'Hanson Close',
                                    'Rinaldo Road',
                                    'Rusham Road',
                                    'Pickets Street',
                                    'Yukon Road',
                                    'Kenilford Road',
                                    'Blandfield Road',
                                    'Ormeley Road',
                                    'Fernlea Road',
                                    'Roseneath Road',
                                    'Balham New Road',
                                    'Badminton Road',
                                    'Devereux Road',
                                    'Clarence Mews',
                                    'Hendrick Avenue',
                                    'Manchuria Road',
                                    'Verran Road',
                                    'Lochinvar Street',
                                    'Kyrle Road',
                                    'Clapham Common West '
                                    'Side',
                                    'Laitwood Road',
                                    'Cavendish Road',
                                    'Nightingale Lane',
                                    'Temperley Road',
                                    'Denning Mews',
                                    'Ramsden Road',
                                    'Penny Mews',
                                    'Sumburgh Road',
                                    'Bracken Avenue',
                                    'Broxash Road',
                                    'Oldridge Road',
                                    'Thurleigh Avenue',
                                    'Hildreth Street',
                                    'The Avenue',
                                    'Bolingbroke Grove',
                                    'Nightingale Walk',
                                    'Ethelbert Street',
                                    'Dinsmore Road',
                                    'Thurleigh Road',
                                    'Balham Grove',
                                    'Lynn Road',
                                    'Ballingdon Road',
                                    'Holmside Road',
                                    'Sudbrooke Road',
                                    'Rossiter Road',
                                    'Balham Hill',
                                    'Westlands Terrace',
                                    'Baldwin Road',
                                    'Balham Station Road',
                                    'Old Park Avenue',
                                    'Clavering Place',
                                    'Hillgate Place',
                                    'Sistova Road',
                                    'Dagnan Road'],
                         'Battersea':
                                  ['Fowler Close',
                                   'Brynmaer Road',
                                   'Ingrave Street',
                                   'Brougham Street',
                                   'Millgrove Street',
                                   'Candahar Road',
                                   'Wolftencroft Close',
                                   'Trinity Road',
                                   'Mantua Street',
                                   'Fairchild Close',
                                   'Usk Road',
                                   'Kennet Close',
                                   'Mcdermott Close',
                                   'Abercrombie Street',
                                   'Este Road',
                                   'Batten Street',
                                   'Nepaul Road',
                                   'Shellwood Road',
                                   'Plough Road',
                                   'Musjid Road',
                                   'Bramlands Close',
                                   'Great Chart Street',
                                   'Weekley Square',
                                   'Odger Street',
                                   'Wye Street',
                                   'Wallis Close',
                                   'Benham Close',
                                   'Wynter Street',
                                   'Falcon Road',
                                   'Parkside Street',
                                   'Dagnall Street',
                                   'Cabul Road',
                                   'Poyntz Road',
                                   'Grant Road',
                                   'Kambala Road',
                                   'Lavender Road',
                                   'Patience Road',
                                   'Henley Street',
                                   'Knowsley Road',
                                   'Beechmore Road',
                                   'Frere Street',
                                   'Matthews Street',
                                   'Cranleigh Mews',
                                   'Longhedge Street',
                                   'Burns Road',
                                   'Kersley Street',
                                   'Kennard Street',
                                   'Chesney Street',
                                   'Reform Street',
                                   'Rowena Crescent',
                                   'Sullivan Close',
                                   'Heaver Road',
                                   'Blondel Street',
                                   'Sheepcote Lane',
                                   'Fawcett Close',
                                   'Hope Street',
                                   'Wayford Street',
                                   'Afghan Road',
                                   'Crombie Mews',
                                   'Winstanley Road',
                                   'Hicks Close',
                                   'Battersea Park Road',
                                   'Albert Bridge Road',
                                   'Chillington Drive',
                                   'Thomas Baines Road',
                                   'Freedom Street',
                                   'Holgate Avenue',
                                   'Maysoule Road',
                                   'Fownes Street',
                                   'Coppock Close',
                                   'Eltringham Street',
                                   'Atherton Street',
                                   'Darien Road',
                                   'Astle Street',
                                   'Falcon Terrace',
                                   'Harpsden Street',
                                   "St James's Grove",
                                   'Petergate',
                                   'Livingstone Road',
                                   'Hibbert Street',
                                   'York Road',
                                   'Lavender Terrace',
                                   'Joubert Street',
                                   'Culvert Road',
                                   'Battersea Bridge '
                                   'Road',
                                   'Falcon Grove',
                                   'Khyber Road',
                                   'Rowditch Lane',
                                   'Lombard Road',
                                   'Orkney Street',
                                   'Meyrick Road',
                                   'Windrush Close',
                                   'Latchmere Road',
                                   'Beverley Close',
                                   'Latchmere Street',
                                   'Newcomen Road',
                                   'Kerrison Road'],
                         'Putney':
                                   ['Greenstead Gardens',
                                    'Woodborough Road',
                                    'Chartfield Avenue',
                                    'Swinburne Road',
                                    'Pettiward Close',
                                    'Cortis Road',
                                    'Holroyd Road',
                                    'Luttrell Avenue',
                                    'Dover House Road',
                                    'Elmshaw Road',
                                    'Queensgate Gardens',
                                    'Torwood Road',
                                    'Montolieu Gardens',
                                    'Lysons Walk',
                                    'Aubyn Square',
                                    'Campion Road',
                                    'Isis Close',
                                    'Marrick Close',
                                    'Mendez Way',
                                    'Cotman Close',
                                    'Larpent Avenue',
                                    'Enmore Road',
                                    'Hobbes Walk',
                                    'Cortis Terrace',
                                    'Hawkesbury Road',
                                    'Bramcote Road',
                                    'Gibbon Walk',
                                    'Balfour Place',
                                    'Dungarvan Avenue',
                                    'Westmead',
                                    'Tideswell Road',
                                    'Akehurst Street',
                                    'Colinette Road',
                                    'Eliot Gardens',
                                    'Briar Walk',
                                    'Coalecroft Road',
                                    'Putney Park Avenue',
                                    'Holford Way',
                                    'Huntingfield Road',
                                    'Parkstead Road',
                                    'Toland Square',
                                    'Granard Avenue',
                                    'Malbrook Road',
                                    'Kingslawn Close',
                                    'Castello Avenue',
                                    'Coppice Drive',
                                    'Fairdale Gardens',
                                    'The Footpath',
                                    'Roehampton Close',
                                    'Fairfax Mews',
                                    "Howard's Lane",
                                    'Telegraph Road',
                                    'Dryburgh Road',
                                    'Roehampton Lane',
                                    'Tildesley Road',
                                    'Breasley Close',
                                    'Putney Heath',
                                    'Daylesford Avenue',
                                    'Sunnymead Road',
                                    'Pullman Gardens',
                                    'Henty Walk',
                                    'Langside Avenue',
                                    'Carslake Road',
                                    'Genoa Avenue',
                                    'William Gardens',
                                    'Solna Avenue',
                                    'Vanneck Square',
                                    'Woodthorpe Road',
                                    'Grosse Way',
                                    'Balmuir Gardens',
                                    'The Pleasance',
                                    "St Margaret's Crescent",
                                    'Parkmead',
                                    'Highdown Road',
                                    'Ellenborough Place',
                                    'Upper Richmond Road',
                                    'Dover Park Drive',
                                    'Innes Gardens',
                                    'Hayward Gardens',
                                    'Hazlewell Road',
                                    'Parkfields',
                                    'Putney Hill',
                                    'Carmalt Gardens',
                                    'Wildcroft Road',
                                    'Lantern Close',
                                    'Dealtry Road',
                                    'Westleigh Avenue',
                                    'Laneway',
                                    'Pleasance Road',
                                    'Crestway',
                                    'Putney Park Lane',
                                    'Wandsworth High Street',
                                    'East Hill'],
                         'Wandsworth':
                                   ['Acris Street',
                                    'Allfarthing Lane',
                                    'Alma Terrace',
                                    'Aslett Street',
                                    'Barmouth Road',
                                    'Baskerville Road',
                                    'Bassingham Road',
                                    'Battersea Rise',
                                    'Beechcroft Road',
                                    'Bevin Square',
                                    'Brightman Road',
                                    'Broadgates Road',
                                    'Brocklebank Road',
                                    'Brodrick Road',
                                    'Bucharest Road',
                                    'Burcote Road',
                                    'Burntwood Close',
                                    'Burntwood Grange '
                                    'Road',
                                    'Burntwood Lane',
                                    'Cader Road',
                                    'Carmichael Mews',
                                    'Chancery Mews',
                                    'Cicada Road',
                                    'Coates Avenue',
                                    'Collamore Avenue',
                                    'College Gardens',
                                    'Crealock Street',
                                    'Crieff Road',
                                    'Daphne Street',
                                    'Dingwall Road',
                                    'Dorlcote Road',
                                    'Earlsfield Road',
                                    'East Hill',
                                    'Ellerton Road',
                                    'Fieldview',
                                    'Fitzhugh Grove',
                                    'Frewin Road',
                                    'Galesbury Road',
                                    'Geraldine Road',
                                    'Glenburnie Road',
                                    'Godley Road',
                                    'Groom Crescent',
                                    'Gunners Road',
                                    'Heathfield Avenue',
                                    'Heathfield Gardens',
                                    'Heathfield Road',
                                    'Heathfield Square',
                                    'Henderson Road',
                                    'Herondale Avenue',
                                    'Huguenot Place',
                                    'Inman Road',
                                    'Jessica Road',
                                    'Jeypore Road',
                                    'John Archer Way',
                                    'Kershaw Close',
                                    'Killarney Road',
                                    'Loxley Road',
                                    'Lyford Road',
                                    'Lyminge Gardens',
                                    'Magdalen Road',
                                    'Marcilly Road',
                                    'Marham Gardens',
                                    'Melody Road',
                                    'Muir Drive',
                                    'Multon Road',
                                    'Nevinson Close',
                                    'Nicosia Road',
                                    'North Side '
                                    'Wandsworth Common',
                                    'Openview',
                                    'Patten Road',
                                    'Quarry Road',
                                    'Routh Road',
                                    'Sandgate Lane',
                                    'Spencer Park',
                                    "St Ann's Hill",
                                    "St Ann's Park Road",
                                    'St Anthonys Close',
                                    'St Benets Close',
                                    'St Catherines Close',
                                    'St Edmunds Close',
                                    'St Hildas Close',
                                    'St Hughes Close',
                                    'St Peters Close',
                                    'Stott Close',
                                    'Strickland Row',
                                    'Swaffield Road',
                                    'Swanage Road',
                                    'Tilehurst Road',
                                    'Titchwell Road',
                                    'Trefoil Road',
                                    'Trinity Road',
                                    'Wandle Road',
                                    'Wandsworth Common '
                                    'West Side',
                                    'Westover Road',
                                    'Wilde Place',
                                    'Wilna Road',
                                    'Windmill Road',
                                    'Winfrith Road']}}}